### ISSUE TITLE
Text element with UTF-8 can't be saved

### ISSUE THREAD

**Issue by MarkJeronimus** [juanfran/svgo-inkscape#4]
Text element with unicode can't be saved:

Traceback (most recent call last):
  File "svgo.inkscape.py", line 75, in <module>
    e.affect(output=False)
  File "D:\0syncedSSD\Portable Progs\InkscapePortable x64\App\Inkscape\share\extensions\inkex.py", line 268, in affect
    self.effect()
  File "svgo.inkscape.py", line 70, in effect
    sys.stdout.write(result.encode("UTF-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 128197: ordinal not in range(128)

0xC3 is the beginning of UTF-8 codepoint \xC3\x97 (this character: ×)

**Comment by juanfran** [comment]
could you try in the last release?

**Comment by tzeumer** [comment]
I had the same problem and the new release fixed it for me. Great :)
