### ISSUE TITLE
Issue saving on Windows

### ISSUE THREAD

**Issue by eek** [juanfran/svgo-inkscape#8]
I have an issue saving an optimized SVG in InkScape on Windows:

```Traceback (most recent call last):
  File "svgo.inkscape.py", line 75, in <module>
    e.affect(output=False)
  File "C:\Program Files\Inkscape\share\extensions\inkex.py", line 283, in affect
    self.effect()
  File "svgo.inkscape.py", line 70, in effect
    sys.stdout.write(result.encode("UTF-8"))
TypeError: write() argument must be str, not bytes
```

**Comment by eek** [comment]
I fixed it by removing `.encode("UTF-8")` from here:

https://github.com/juanfran/svgo-inkscape/blob/13a4a74784cb63e7dca7ab6d5e99415362bf1be1/svgo-inkscape/svgo.inkscape.py#L70
